# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: 'spring'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Configure Docker buildx
      inputs:
        targetType: 'inline'
        script: |
          docker run --rm --privileged tonistiigi/binfmt --install all
          docker buildx create --platform "linux/amd64,linux/arm64,linux/arm/v7" --use
          docker buildx install
    - task: Docker@2
      inputs:
        repository: 'todo-api'
        command: 'build'
        Dockerfile: 'api-spring/Dockerfile'
        tags: |
          $(Build.BuildId)
          spring
        arguments: '--platform "linux/amd64,linux/arm64,linux/arm/v7"'

