# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'spring'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          ls
          docker run --rm --privileged tonistiigi/binfmt --install all
          docker buildx create --platform "linux/amd64,linux/arm64,linux/arm/v7" --use
          docker buildx build  --platform "linux/amd64,linux/arm64,linux/arm/v7" ./api-spring -t $(Build.BuildId) -t spring

