name: API-Spring Docker Image

on:
  push:
    branches:
      - 'master'
    paths:
      - 'api-spring/**'
      - '.github/workflows/api-spring-docker.yml'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api-spring
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:spring
          platforms: "linux/amd64,linux/arm64,linux/arm/v7" 
          
