name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'api-spring/**'
      - '.github/workflows/docker-image.yml'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Build the Docker image
        run: docker build ./api-spring --tag my-image-name:$(date +%s)
