name: API-Spring Docker Image

on:
  push:
    branches:
      - 'master'
    paths:
      - 'api-spring/**'
      - '.github/workflows/docker-image.yml'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build ./api-spring --tag michaelburch/todo-api:spring -t $(date +%s) --push
